# permissions for end users to edit s3buckets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: s3bucket-editor-role
rules:
- apiGroups:
  - aws.services.io
  resources:
  - s3buckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.services.io
  resources:
  - s3buckets/status
  verbs:
  - get
